### ISSUE TITLE
LocalId vs Server ID in ISynchronizable (Can you create slack for this awesome SDK)

### ISSUE THREAD

**Issue by chrisgate** [winstongubantes/matchasync#4]
Coming from Azure Mobile App can you state why we have two IDs instead of one for both server and mobile:
 public class Synchronizable : ISynchronizable
    {
        public long Id { get; set; } //THIS IS SERVER ID
        public string LocalId { get; set; } //THIS IS GUID FOR MOBILE USE
        public bool IsSynced { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime LastUpdated { get; set; }
    }

I am more curious about offline first of this awesome SDK.

Do u have blog on this awesome SDK aside the doc. if yes can you point me to it

Thanks @winstongubantes

**Comment by winstongubantes** [comment]
Hi @chrisgate , That is  typical to have only one Id both server and mobile. The reason behind for having both a serverid (long or int type) and localid(guid for mobile) is that when on offline mode and there is no way that we could get the server generated id and the only way to distinguish a record is tru GUID (generally accepted for having unique id) and since we want the server id to remain long or int type to make it indexable (for db performance) so we decided to have both the server id and local id (PS. LocalID is automatically generated when the record is created in the mobile and the server id is default value). Hope it helps.

**Comment by chrisgate** [comment]
Thanks @winstongubantes.
Can i  paint a scenario here?

If I once load this app and next time no internet,will it load from local?

Is this awesome library offline first like Azure Mobile apps?


Thanks

**Comment by winstongubantes** [comment]
@chrisgate yes it will load from local when no internet and btw this is designed with no-internet-first approached.

yes, the inspiration comes from azure mobile apps but we decided to create one to make it customizable and in-premise friendly.

**Comment by chrisgate** [comment]
@winstongubantes wow, that make me love it more.

Think is something i am missing or i am doing it in azure mobile apps pattern.

Thanks
